### ISSUE TITLE
Still problems with accessing menues

### ISSUE THREAD

**Issue by macardi** [Ikosse/plugin.video.teliaplay-se#2]
Hi,

I still have problems with accessing some menu entries where the following error appears when I try to open a menu entry “PERSISTED_QUERY_NOT_FOUND”. It worked for a while after your fix, but the issue have come back.

[Log](https://paste.kodi.tv/ecejefusif.kodi)

Regards
Marcus

**Comment by Ikosse** [comment]
Hello,

Yes, this problem stems from Telia changing their graphql hashes, which causes problems since I have hard coded them in my add-on. I'm currently working on finding a way to update the hashes automatically instead. Until I have figured this out I will keep updating the hashes manually as soon as I get some spare time.

Kind regards,
Ikosse

**Comment by macardi** [comment]
Ok, I see! Thanks for looking into it. Hope you find a fix.

**Comment by macardi** [comment]
This problem is back again I am afraid. Did you found a solution for updating the hashes automatic?

**Comment by Ikosse** [comment]
Hello,

Thanks for reporting again. I have not had the time to look into it. But a temporary solution I have thought about is uploading new hashes to github every once in a while and then add functionality to the settings of the add-on to download these hashes. That will at least prevent me from having to make a new pull request to the kodi repository any time the hashes changes.

**Comment by Ikosse** [comment]
I retrieve them by inspecting requests sent from my browser. But don't bother; I wrote a small add-on for the purpose and can get them with relative ease. Instead I propose keeping this issue open, and whenever you notice the error you can just report here and I will update them as soon possible. With the lastest version of the add-on (not yet in the official kodi repository) you can then sync the hashes. Later I will automate this process, so there will be no need to manually sync.

**Comment by Ikosse** [comment]
In order to put as little strain as possible on the user, I decided to force the add-on to always use the hashes uploaded in a dedicated repository. Therefore there is no need for the user to manually sync. So you only need to report the problem here and wait for me to upload new hashes, and the issue should resolve.

**Comment by macardi** [comment]
Ok thanks! I will download and test the latest version.

**Comment by Ikosse** [comment]
Great, I have uploaded the latest hashes and hopefully it should work! I will close this issue, and instead you can notify me here when the hashes become obsolete: https://github.com/Ikosse/teliaplay-graphql-hashes/issues/1

**Comment by Ikosse** [comment]
Great, I have uploaded the latest hashes and hopefully it should work! I will close this issue, and instead you can notify me here when the hashes become obsolete: https://github.com/Ikosse/teliaplay-graphql-hashes/issues/1
